sticker_images:
  default: >-
    []
  json_schema: >-
    {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "emoji": {
            "type": "string"
          },
          "previewUrl": {
            "type": "string"
          },
          "markdownUrl": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
    
composer_icon:
  type: string
  default: "far-note-sticky"
  description: "Add icon to Sticker composer button."
svg_icons: 
  default: "far-note-sticky"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 6 icons used in this theme component"
stickers_shadow:
  type: bool
  default: true
  description: "Add shadow to stickers."
